### ISSUE TITLE
Link !

### ISSUE THREAD

**Issue by sayeedajmal** [fatim-uz-zohra/Fz-e-commerce#1]
Please Provide Link of the Website

**Comment by fatim-uz-zohra** [comment]
> Please Provide Link of the Website

where??

**Comment by sayeedajmal** [comment]
> > Please Provide Link of the Website
> 
> where??
> 

* Open Github in PC for full github Services.
* Go to the repository.
* Click on Setting which is labeled on right top corner of the repository. 
* Scroll Down and fill your website link in given field of labeled `Link`.
